alias -g reload-aliases="source ~/.config/aliases.zsh"
alias please="sudo"
#alias -g install="pacman -S"
#alias -g update="pacman -Suy"
#alias -g remove="pacman -Rcs"
alias -g installfzf="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias -g aurfzf="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro sudo yay -S"
alias -g removefzf="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias -g sha512="sha512sum"
alias -g pyvenv="python -m venv venv & source venv/bin/activate"
alias -g x="QT_QPA_PLATFORM=xcb"
alias -g aur="yay"
#alias -g arm="source /home/muf/scripts/arm"
#alias -g arm="aur -U https://archive.archlinux.org/packages/.all/\$(curl -s https://archive.archlinux.org/packages/.all/index.0.xz | unxz | grep $1 | fzf).pkg.tar.zst"
#alias -g youtube-dl="yt-dlp"
alias -g open="xdg-open"
alias -g la="ls -la"
alias -g ll="ls -l"
alias -g mkdir="mkdir -p"
alias -g ls="EXA_COLORS="xx=2" eza --icons"
alias -g cat="bat"
alias -g betterdiscord-installer="betterdiscord-installer 2> /dev/null"
alias -g to-idle="systemd-run -S --user -p CPUWeight=idle -p IOWeight=1"
